import {
  ShoppingBag,
  Users2,
  Briefcase,
  Dumbbell,
  HeartPulse,
  ShoppingBasket,
  ShoppingCart,
  Plane,
  MapPinned,
  Receipt,
  Banknote,
  HandCoins,
  MessagesSquare,
  House,
  SprayCan,
  RollerCoaster,
  FerrisWheel,
  Drama,
  Theater,
  Film,
  University,
  Book,
  SquareLibrary,
  Building,
  Building2,
} from "lucide-react";
import { CategoryIcon } from "./category.types";

export const categoryIcons: CategoryIcon[] = [
  { id: 1, name: "shopping-bag", icon: <ShoppingBag /> },
  { id: 2, name: "users", icon: <Users2 /> },
  { id: 3, name: "briefcase", icon: <Briefcase /> },
  { id: 4, name: "dumbbell", icon: <Dumbbell /> },
  { id: 5, name: "heart-pulse", icon: <HeartPulse /> },
  { id: 6, name: "shopping-basket", icon: <ShoppingBasket /> },
  { id: 7, name: "shopping-cart", icon: <ShoppingCart /> },
  { id: 8, name: "plane", icon: <Plane /> },
  { id: 9, name: "map-pinned", icon: <MapPinned /> },
  { id: 10, name: "receipt", icon: <Receipt /> },
  { id: 11, name: "banknote", icon: <Banknote /> },
  { id: 12, name: "hand-coins", icon: <HandCoins /> },
  { id: 13, name: "messages-square", icon: <MessagesSquare /> },
  { id: 14, name: "house", icon: <House /> },
  { id: 15, name: "spray-can", icon: <SprayCan /> },
  { id: 16, name: "roller-coaster", icon: <RollerCoaster /> },
  { id: 17, name: "ferris-wheel", icon: <FerrisWheel /> },
  { id: 18, name: "drama", icon: <Drama /> },
  { id: 19, name: "theater", icon: <Theater /> },
  { id: 20, name: "film", icon: <Film /> },
  { id: 21, name: "university", icon: <University /> },
  { id: 22, name: "book", icon: <Book /> },
  { id: 23, name: "square-library", icon: <SquareLibrary /> },
  { id: 24, name: "building", icon: <Building /> },
  { id: 25, name: "building-2", icon: <Building2 /> },
];
